{smcl}
{* *! version 1.0  March 2014}{...}
{vieweralsosee "mirubin" "help mirubin"}{...}
{vieweralsosee "" "--"}{...}
{vieweralsosee "[MI] mi" "help mi"}{...}
{vieweralsosee "[MI] mi estimate" "help mi estimate"}{...}
{viewerjumpto "Syntax" "mipllest##syntax"}{...}
{viewerjumpto "Description" "mipllest##description"}{...}
{viewerjumpto "Options" "mipllest##options"}{...}
{viewerjumpto "Known issues" "mipllest##issues"}{...}
{viewerjumpto "Examples" "mipllest##examples"}{...}
{viewerjumpto "Stored results" "mipllest##results"}{...}
{title:Title}


    {cmd:mipllest} {hline 2} Parallel estimation for multiple imputed datasets {...}
(Requires George Vega Yon's -{net "describe parallel, from(http://fmwww.bc.edu/RePEc/bocode/p)":parallel}-){...}
{right:(Version 1.0)}


{marker syntax}{...}
{title:Syntax}

{phang}
Obtain MI estimates similar to Stata's -{help mi estimate}-

{p 8 16 2}
{cmd:mipllest} [{cmd:,} {it:options}] {cmd::} {it:{help mi_estimation##estimation_command:estimation_command}} ...


{phang}
To debug by viewing logs of estimations done in different clusters... 

{p 8 16 2}
{cmd:mipllest debug} [{cmd:,} {it:debug_options}] 


{synoptset 29 tabbed}{...}
{synopthdr}
{synoptline}
{syntab:Main}
{synopt:{opth i:mputations(numlist)}}specify which imputations to use{p_end}
{synopt:{opt stub(name)}}specify the stub of the estimation results{p_end}
{synopt:{opt keep}}keep auxiliary files generated by {cmd:mipllest}{p_end}
{synopt:{opt replace}}allow existing estimates in memory to be overwritten{p_end}
{synopt:{opt pll:opts(parallel_options)}}Options to be passed to {help parallel}{p_end}
{synoptline}
{p2colreset}{...}
{p 4 6 2}
You must {cmd:mi set} your data before using {cmd:mipllest};
see {manhelp mi_set MI:mi set}.{p_end}


{marker debug_options}{...}
{synoptset 29}{...}
{synopthdr:debug_options}
{synoptline}
{synopt:{opt pll:_id(pll_id)}}specify {it:pll_id}{p_end}
{synopt:{opt pll_dir(pll_dir)}}specify {it:pll_dir}{p_end}
{synoptline}
{p2colreset}{...}


{marker description}{...}
{title:Description}

{pstd}
{cmd:mipllest} allows parallel estimation of 
{it:{help mi_estimation##estimation_command:estimation_command}} by making use of 
George Vega Yon's -{net "describe parallel, from(http://fmwww.bc.edu/RePEc/bocode/p)":parallel}-,
which starts multiple instances of Stata to perform parallel processing 
and therefore does not require Stata MP. {cmd:mipllest} saves estimation results using 
{help estimates store}. Results from estimation are saved with names 
{it:stub}1, {it:stub}2, etc., where {it:stub} is either a user-supplied name or
{it:_mipllest_}. Estimates from different imputed datasets can be combined together using
{help mirubin}. 

{pstd}
Before using {cmd:mipllest} users are advised to familiarize themselves with the behaviour of
{help parallel}. 

{marker options}{...}
{title:Options}

{dlgtab:options}

{phang}
{opth imputations(numlist)} specifies which imputations to use.  The
default is to use all of them.  

{phang}
{opt stub(name)} specifies the stub of names of the estimation results from the 
different imputed datasets. If {opt stub(name)} is not specified, it defaults to 
{it:_mipllest_}. After running {cmd:mipllest}, type "{cmd:est dir} {it:stub}{cmd:*}"
to see the estimated results. 

{phang}
{cmd:keep} specifies that auxiliary files created by {cmd:mipllest} be kept. 
{cmd:mipllest} causes each of the clusters to run the estimation in parallel
and save the results as temporary {it:_mipllest_#.ster} files using {help estimates save}, 
where {it:#} are the numbers 
given in {cmd:imputations(numlist)} or else the values of _mi_m. {cmd:keep} requests that
these files be kept, as well as the {it:_mipllest_script.do} file which is run by the 
parallel clusters. 

{phang}
{cmd:replace} specifies that the estimation results {it:stub}1, {it:stub}2, etc. can be over-written.  

{phang}
{opt pllopts(parallel_options)} passes additional options to {cmd:parallel}. A
particularly useful command to pass is {cmd:keep}, which requests that the auxiliary
files produced by {cmd:parallel} be kept also.   

{dlgtab:debug_options}

{pstd}
Usually, {cmd:mipllest debug} can only be used after we have run {cmd:mipllest} with 
the {cmd:pllotps(keep)} option. This option requests that the log files created by 
{help parallel} be kept. The log files show the log of the estimation commands performed
in the different clusters, and as of 26/3/2014, have the form 
{cmd:__pll}{it:pll_id}{cmd:_do}{it:#}{cmd:.log}, where {it:pll_id} is a unique ID given 
to a particular {cmd:parallel} task and {it:#} is the cluster number. {cmd:mipllest debug} then brings up
these log files in the viewer to assist debugging. 

{phang}
{opt pll_id(pll_id)} specifies the {it:pll_id} which identifies the log files created by 
{cmd:parallel} that are to be displayed. If {opt pll_id(pll_id)} is not specified, then
{cmd:mipllest debug} searches for {cmd:r(pll_id)} from the previous {cmd:parallel} 
command. Sometimes, {cmd:r(pll_id)} may not exist, or is overwritten by subsequent commands. 
This is especially the case where {cmd:parallel} ended with a break or an error. 
However, in these instances the log files are often kept, even if the user did not specify the 
{cmd:pllopts(keep)} option. Here, users can supply {cmd:r(pll_id)}
manually to identify them. 

{phang}
{opt pll_dir(pll_dir)} specifies the directory where the log files created by 
{cmd:parallel} are kept. If {opt pll_id(pll_id)} is not specified, then
{cmd:mipllest debug} searches for {cmd:r(pll_dir)} from the previous {cmd:parallel} 
command, and failing that, assumes the current directory.  

{marker issues}{...}
{title:Known issues}

{phang}
.  Datasets with {help tempvar:temporary variables}, especially "__000000" and "__000001" can 
somestimes (but not always) cause estimation to fail in the clusters. 

{phang}
.  In theory, users can supply their own estimation commands instead of those 
{help mi_estimation##estimation_command:listed}. However, this should be done in extreme caution
as during testing it has been found that some commands such as {help preserve}, or 
{help mi xeq} can cause interference between clusters when running {help parallel}. Likewise, 
the use of {help tempfile} should be avoided. 
{p_end}


{marker examples}{...}
{title:Example}

{phang2}
{cmd:parallel setclusters 2}
{p_end}
{phang2}
{cmd:webuse mheart1s20}
{p_end}
{phang2}
{cmd:mi describe}
{p_end}
{phang2}
{cmd:mipllest: logit attack smokes age bmi hsgrad female}
{p_end}
{phang2}
{cmd:est dir _mipllest_*}
{p_end}


{marker results}{...}
{title:Stored results}

{pstd}
{cmd:mipllest} does not create additional {cmd:r()} or {cmd:e()} results. However, 
the {cmd:r()} macros stored when using {help parallel} are retained. The macros
{cmd:r(pll_id)} is particularly useful. See the options for {opt pll_id(pll_id)} above. 
{p_end}

{marker author}{...}
{title:Author}

    Timothy Mak, University of Hong Kong
    tshmak@hku.hk
    March 2014

	
	