/***** National Capabilities dataset (I09904) codes *****/

program k_capc
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "afgn"
replace NAMES_STD = "Albania" if NAMES_STD == "albn"
replace NAMES_STD = "Algeria" if NAMES_STD == "algr"
replace NAMES_STD = "Angola" if NAMES_STD == "angl"
replace NAMES_STD = "Argentina" if NAMES_STD == "argn"
replace NAMES_STD = "Australia" if NAMES_STD == "ausl"
replace NAMES_STD = "Austria" if NAMES_STD == "aust"
replace NAMES_STD = "Bahrain" if NAMES_STD == "bhrn"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "bngl"
replace NAMES_STD = "Barbados" if NAMES_STD == "brbd"
replace NAMES_STD = "Belgium" if NAMES_STD == "blgm"
replace NAMES_STD = "Belize" if NAMES_STD == "bnin"
replace NAMES_STD = "Bhutan" if NAMES_STD == "bhtn"
replace NAMES_STD = "Bolivia" if NAMES_STD == "bolv"
replace NAMES_STD = "Botswana" if NAMES_STD == "btsn"
replace NAMES_STD = "Brazil" if NAMES_STD == "brzl"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "blgr"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "bkfs"
replace NAMES_STD = "Burundi" if NAMES_STD == "brnd"
replace NAMES_STD = "Cambodia" if NAMES_STD == "kmpc"
replace NAMES_STD = "Cameroon" if NAMES_STD == "cmrn"
replace NAMES_STD = "Canada" if NAMES_STD == "cnda"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "cvrd"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "cafr"
replace NAMES_STD = "Chad" if NAMES_STD == "chad"
replace NAMES_STD = "Chile" if NAMES_STD == "chle"
replace NAMES_STD = "China" if NAMES_STD == "chna"
replace NAMES_STD = "Colombia" if NAMES_STD == "clmb"
replace NAMES_STD = "Comoros" if NAMES_STD == "cmrs"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "zair"
replace NAMES_STD = "Congo" if NAMES_STD == "cngo"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "crca"
replace NAMES_STD = "Cuba" if NAMES_STD == "cuba"
replace NAMES_STD = "Cyprus" if NAMES_STD == "cypr"
replace NAMES_STD = "Czechoslovakia" if NAMES_STD == "czch"
replace NAMES_STD = "Denmark" if NAMES_STD == "dnmk"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "dmnr"
replace NAMES_STD = "Ecuador" if NAMES_STD == "ecdr"
replace NAMES_STD = "Egypt" if NAMES_STD == "egpt"
replace NAMES_STD = "El Salvador" if NAMES_STD == "elsl"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "eqgn"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "ethp"
replace NAMES_STD = "Fiji" if NAMES_STD == "fiji"
replace NAMES_STD = "Finland" if NAMES_STD == "fnld"
replace NAMES_STD = "France" if NAMES_STD == "frnc"
replace NAMES_STD = "Gabon" if NAMES_STD == "gbon"
replace NAMES_STD = "Gambia" if NAMES_STD == "gmba"
replace NAMES_STD = "German Democratic Republic" if NAMES_STD == "gdr0"
replace NAMES_STD = "Germany" if NAMES_STD == "gfr0"
replace NAMES_STD = "Ghana" if NAMES_STD == "ghna"
replace NAMES_STD = "Greece" if NAMES_STD == "grce"
replace NAMES_STD = "Grenada" if NAMES_STD == "grnd"
replace NAMES_STD = "Guatemala" if NAMES_STD == "gtml"
replace NAMES_STD = "Guinea" if NAMES_STD == "gnea"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "gnbs"
replace NAMES_STD = "Guyana" if NAMES_STD == "gyna"
replace NAMES_STD = "Haiti" if NAMES_STD == "hati"
replace NAMES_STD = "Honduras" if NAMES_STD == "hnds"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "hgkg"
replace NAMES_STD = "Hungary" if NAMES_STD == "hngr"
replace NAMES_STD = "Iceland" if NAMES_STD == "icld"
replace NAMES_STD = "India" if NAMES_STD == "inda"
replace NAMES_STD = "Indonesia" if NAMES_STD == "inds"
replace NAMES_STD = "Iran" if NAMES_STD == "iran"
replace NAMES_STD = "Iraq" if NAMES_STD == "iraq"
replace NAMES_STD = "Ireland" if NAMES_STD == "irld"
replace NAMES_STD = "Israel" if NAMES_STD == "isrl"
replace NAMES_STD = "Italy" if NAMES_STD == "itly"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "ivct"
replace NAMES_STD = "Jamaica" if NAMES_STD == "jmca"
replace NAMES_STD = "Japan" if NAMES_STD == "jpan"
replace NAMES_STD = "Jordan" if NAMES_STD == "jrdn"
replace NAMES_STD = "Kenya" if NAMES_STD == "knya"
replace NAMES_STD = "South Korea" if NAMES_STD == "kors"
replace NAMES_STD = "North Korea" if NAMES_STD == "korn"
replace NAMES_STD = "Kuwait" if NAMES_STD == "kwat"
replace NAMES_STD = "Laos" if NAMES_STD == "laos"
replace NAMES_STD = "Lebanon" if NAMES_STD == "lbnn"
replace NAMES_STD = "Lesotho" if NAMES_STD == "lsto"
replace NAMES_STD = "Liberia" if NAMES_STD == "lbra"
replace NAMES_STD = "Libya" if NAMES_STD == "lbya"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "lxbg"
replace NAMES_STD = "Madagascar" if NAMES_STD == "mdgs"
replace NAMES_STD = "Malawi" if NAMES_STD == "mlwi"
replace NAMES_STD = "Malaysia" if NAMES_STD == "mlys"
replace NAMES_STD = "Maldives" if NAMES_STD == "mldv"
replace NAMES_STD = "Mali" if NAMES_STD == "mali"
replace NAMES_STD = "Malta" if NAMES_STD == "mlta"
replace NAMES_STD = "Mauritania" if NAMES_STD == "mrtn"
replace NAMES_STD = "Mauritius" if NAMES_STD == "mrts"
replace NAMES_STD = "Mexico" if NAMES_STD == "mxco"
replace NAMES_STD = "Mongolia" if NAMES_STD == "mngl"
replace NAMES_STD = "Morocco" if NAMES_STD == "mrco"
replace NAMES_STD = "Mozambique" if NAMES_STD == "mzbq"
replace NAMES_STD = "Myanmar" if NAMES_STD == "brma"
replace NAMES_STD = "Nepal" if NAMES_STD == "npal"
replace NAMES_STD = "Netherlands" if NAMES_STD == "nthl"
replace NAMES_STD = "New Zealand" if NAMES_STD == "nzld"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "ncrg"
replace NAMES_STD = "Niger" if NAMES_STD == "nger"
replace NAMES_STD = "Nigeria" if NAMES_STD == "ngra"
replace NAMES_STD = "Norway" if NAMES_STD == "nrwy"
replace NAMES_STD = "Oman" if NAMES_STD == "oman"
replace NAMES_STD = "Pakistan" if NAMES_STD == "pkst"
replace NAMES_STD = "Panama" if NAMES_STD == "pnma"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "ppng"
replace NAMES_STD = "Paraguay" if NAMES_STD == "prgy"
replace NAMES_STD = "Peru" if NAMES_STD == "peru"
replace NAMES_STD = "Philippines" if NAMES_STD == "phlp"
replace NAMES_STD = "Poland" if NAMES_STD == "plnd"
replace NAMES_STD = "Portugal" if NAMES_STD == "prtg"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "prtr"
replace NAMES_STD = "Qatar" if NAMES_STD == "qtar"
replace NAMES_STD = "Romania" if NAMES_STD == "rmna"
replace NAMES_STD = "Russia" if NAMES_STD == "ussr"
replace NAMES_STD = "Rwanda" if NAMES_STD == "rwnd"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "stpr"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "sdar"
replace NAMES_STD = "Senegal" if NAMES_STD == "sngl"
replace NAMES_STD = "Seychelles" if NAMES_STD == "sych"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "srle"
replace NAMES_STD = "Singapore" if NAMES_STD == "sngp"
replace NAMES_STD = "Somalia" if NAMES_STD == "smla"
replace NAMES_STD = "South Africa" if NAMES_STD == "safr"
replace NAMES_STD = "Spain" if NAMES_STD == "span"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "srlk"
replace NAMES_STD = "Suriname" if NAMES_STD == "srnm"
replace NAMES_STD = "Swaziland" if NAMES_STD == "swaz"
replace NAMES_STD = "Sweden" if NAMES_STD == "swdn"
replace NAMES_STD = "Switzerland" if NAMES_STD == "swtz"
replace NAMES_STD = "Syria" if NAMES_STD == "syra"
replace NAMES_STD = "Taiwan" if NAMES_STD == "twan"
replace NAMES_STD = "Tanzania" if NAMES_STD == "tnzn"
replace NAMES_STD = "Thailand" if NAMES_STD == "tlnd"
replace NAMES_STD = "Togo" if NAMES_STD == "togo"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "trnt"
replace NAMES_STD = "Tunisia" if NAMES_STD == "tnsa"
replace NAMES_STD = "Turkey" if NAMES_STD == "trky"
replace NAMES_STD = "Uganda" if NAMES_STD == "ugnd"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "uar0"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "uk00"
replace NAMES_STD = "United States" if NAMES_STD == "usa0"
replace NAMES_STD = "Uruguay" if NAMES_STD == "urgy"
replace NAMES_STD = "Venezuela" if NAMES_STD == "vnzl"
replace NAMES_STD = "Vietnam" if NAMES_STD == "vnm0"
replace NAMES_STD = "Republic of Vietnam" if NAMES_STD == "vnms"
replace NAMES_STD = "Samoa" if NAMES_STD == "wsma"
replace NAMES_STD = "Yemen" if NAMES_STD == "ynms"
replace NAMES_STD = "Yemen Arab Republic" if NAMES_STD == "ynms"
replace NAMES_STD = "Yemen People's Republic" if NAMES_STD == "ymna"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "ygsl"
replace NAMES_STD = "Zambia" if NAMES_STD == "zmba"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "zimb"

end
exit
