/***** Correlates of War codes *****/
/***** equivalent to: cow, eug, icb, mar, mid, pol *****/

program k_cown
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "700"
replace NAMES_STD = "Albania" if NAMES_STD == "339"
replace NAMES_STD = "Algeria" if NAMES_STD == "615"
replace NAMES_STD = "Andorra" if NAMES_STD == "232"
replace NAMES_STD = "Angola" if NAMES_STD == "540"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "58"
replace NAMES_STD = "Argentina" if NAMES_STD == "160"
replace NAMES_STD = "Armenia" if NAMES_STD == "371"
replace NAMES_STD = "Australia" if NAMES_STD == "900"
replace NAMES_STD = "Austria" if NAMES_STD == "305"
replace NAMES_STD = "Austria-Hungary" if NAMES_STD == "300"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "373"
replace NAMES_STD = "Baden" if NAMES_STD == "267"
replace NAMES_STD = "Bahamas" if NAMES_STD == "31"
replace NAMES_STD = "Bahrain" if NAMES_STD == "692"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "771"
replace NAMES_STD = "Barbados" if NAMES_STD == "53"
replace NAMES_STD = "Bavaria" if NAMES_STD == "245"
replace NAMES_STD = "Belarus" if NAMES_STD == "370"
replace NAMES_STD = "Belgium" if NAMES_STD == "211"
replace NAMES_STD = "Belize" if NAMES_STD == "80"
replace NAMES_STD = "Benin" if NAMES_STD == "434"
replace NAMES_STD = "Bhutan" if NAMES_STD == "760"
replace NAMES_STD = "Bolivia" if NAMES_STD == "145"
replace NAMES_STD = "Bosnia and Herzegovina" if NAMES_STD == "346"
replace NAMES_STD = "Botswana" if NAMES_STD == "571"
replace NAMES_STD = "Brazil" if NAMES_STD == "140"
replace NAMES_STD = "Brunei" if NAMES_STD == "835"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "355"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "439"
replace NAMES_STD = "Burundi" if NAMES_STD == "516"
replace NAMES_STD = "Cambodia" if NAMES_STD == "811"
replace NAMES_STD = "Cameroon" if NAMES_STD == "471"
replace NAMES_STD = "Canada" if NAMES_STD == "20"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "402"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "482"
replace NAMES_STD = "Chad" if NAMES_STD == "483"
replace NAMES_STD = "Chile" if NAMES_STD == "155"
replace NAMES_STD = "China" if NAMES_STD == "710"
replace NAMES_STD = "Colombia" if NAMES_STD == "100"
replace NAMES_STD = "Comoros" if NAMES_STD == "581"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "490"
replace NAMES_STD = "Congo" if NAMES_STD == "484"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "94"
replace NAMES_STD = "Croatia" if NAMES_STD == "344"
replace NAMES_STD = "Cuba" if NAMES_STD == "40"
replace NAMES_STD = "Cyprus" if NAMES_STD == "352"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "316"
replace NAMES_STD = "Czechoslovakia" if NAMES_STD == "315"
replace NAMES_STD = "Denmark" if NAMES_STD == "390"
replace NAMES_STD = "Djibouti" if NAMES_STD == "522"
replace NAMES_STD = "Dominica" if NAMES_STD == "54"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "42"
replace NAMES_STD = "Timor" if NAMES_STD == "860"
replace NAMES_STD = "Ecuador" if NAMES_STD == "130"
replace NAMES_STD = "Egypt" if NAMES_STD == "651"
replace NAMES_STD = "El Salvador" if NAMES_STD == "92"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "411"
replace NAMES_STD = "Eritrea" if NAMES_STD == "531"
replace NAMES_STD = "Estonia" if NAMES_STD == "366"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "530" | NAMES_STD == "529"
replace NAMES_STD = "Fiji" if NAMES_STD == "950"
replace NAMES_STD = "Finland" if NAMES_STD == "375"
replace NAMES_STD = "France" if NAMES_STD == "220"
replace NAMES_STD = "Gabon" if NAMES_STD == "481"
replace NAMES_STD = "Gambia" if NAMES_STD == "420"
replace NAMES_STD = "Georgia" if NAMES_STD == "372"
replace NAMES_STD = "German Democratic Republic" if NAMES_STD == "265"
//255 = unified Germany, 260 = German Federal Republic
replace NAMES_STD = "Germany" if NAMES_STD == "255" | NAMES_STD == "260"
replace NAMES_STD = "Ghana" if NAMES_STD == "452"
replace NAMES_STD = "Greece" if NAMES_STD == "350"
replace NAMES_STD = "Grenada" if NAMES_STD == "55"
replace NAMES_STD = "Guatemala" if NAMES_STD == "90"
replace NAMES_STD = "Guinea" if NAMES_STD == "438"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "404"
replace NAMES_STD = "Guyana" if NAMES_STD == "110"
replace NAMES_STD = "Haiti" if NAMES_STD == "41"
replace NAMES_STD = "Hanover" if NAMES_STD == "240"
replace NAMES_STD = "Hesse Electoral" if NAMES_STD == "273"
replace NAMES_STD = "Hesse Grand Ducal" if NAMES_STD == "275"
replace NAMES_STD = "Honduras" if NAMES_STD == "91"
replace NAMES_STD = "Hungary" if NAMES_STD == "310"
replace NAMES_STD = "Iceland" if NAMES_STD == "395"
replace NAMES_STD = "India" if NAMES_STD == "750"
replace NAMES_STD = "Indonesia" if NAMES_STD == "850"
replace NAMES_STD = "Iran" if NAMES_STD == "630"
replace NAMES_STD = "Iraq" if NAMES_STD == "645"
replace NAMES_STD = "Ireland" if NAMES_STD == "205"
replace NAMES_STD = "Israel" if NAMES_STD == "666"
replace NAMES_STD = "Italy" if NAMES_STD == "325"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "437"
replace NAMES_STD = "Jamaica" if NAMES_STD == "51"
replace NAMES_STD = "Japan" if NAMES_STD == "740"
replace NAMES_STD = "Jordan" if NAMES_STD == "663"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "705"
replace NAMES_STD = "Kenya" if NAMES_STD == "501"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "703"
replace NAMES_STD = "Kiribati" if NAMES_STD == "946"
replace NAMES_STD = "South Korea" if NAMES_STD == "730" | NAMES_STD == "732"
replace NAMES_STD = "North Korea" if NAMES_STD == "731"
replace NAMES_STD = "Kuwait" if NAMES_STD == "690"
replace NAMES_STD = "Laos" if NAMES_STD == "812"
replace NAMES_STD = "Latvia" if NAMES_STD == "367"
replace NAMES_STD = "Lebanon" if NAMES_STD == "660"
replace NAMES_STD = "Lesotho" if NAMES_STD == "570"
replace NAMES_STD = "Liberia" if NAMES_STD == "450"
replace NAMES_STD = "Libya" if NAMES_STD == "620"
replace NAMES_STD = "Liechtenstein" if NAMES_STD == "223"
replace NAMES_STD = "Lithuania" if NAMES_STD == "368"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "212"
replace NAMES_STD = "Macedonia" if NAMES_STD == "343"
replace NAMES_STD = "Madagascar" if NAMES_STD == "580"
replace NAMES_STD = "Malawi" if NAMES_STD == "553"
replace NAMES_STD = "Malaysia" if NAMES_STD == "820"
replace NAMES_STD = "Maldives" if NAMES_STD == "781"
replace NAMES_STD = "Mali" if NAMES_STD == "432"
replace NAMES_STD = "Malta" if NAMES_STD == "338"
replace NAMES_STD = "Marshall Islands" if NAMES_STD == "983"
replace NAMES_STD = "Mauritania" if NAMES_STD == "435"
replace NAMES_STD = "Mauritius" if NAMES_STD == "590"
replace NAMES_STD = "Meckelnburg Schwerin" if NAMES_STD == "280"
replace NAMES_STD = "Mexico" if NAMES_STD == "70"
replace NAMES_STD = "Micronesia" if NAMES_STD == "987"
replace NAMES_STD = "Modena" if NAMES_STD == "332"
replace NAMES_STD = "Moldova" if NAMES_STD == "359"
replace NAMES_STD = "Monaco" if NAMES_STD == "221"
replace NAMES_STD = "Mongolia" if NAMES_STD == "712"
replace NAMES_STD = "Morocco" if NAMES_STD == "600"
replace NAMES_STD = "Mozambique" if NAMES_STD == "541"
replace NAMES_STD = "Myanmar" if NAMES_STD == "775"
replace NAMES_STD = "Namibia" if NAMES_STD == "565"
replace NAMES_STD = "Nauru" if NAMES_STD == "970"
replace NAMES_STD = "Nepal" if NAMES_STD == "790"
replace NAMES_STD = "Netherlands" if NAMES_STD == "210"
replace NAMES_STD = "New Zealand" if NAMES_STD == "920"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "93"
replace NAMES_STD = "Niger" if NAMES_STD == "436"
replace NAMES_STD = "Nigeria" if NAMES_STD == "475"
replace NAMES_STD = "Norway" if NAMES_STD == "385"
replace NAMES_STD = "Oman" if NAMES_STD == "698"
replace NAMES_STD = "Pakistan" if NAMES_STD == "770"
replace NAMES_STD = "Palau" if NAMES_STD == "986"
replace NAMES_STD = "Panama" if NAMES_STD == "95"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "910"
replace NAMES_STD = "Paraguay" if NAMES_STD == "150"
replace NAMES_STD = "Parma" if NAMES_STD == "335"
replace NAMES_STD = "Peru" if NAMES_STD == "135"
replace NAMES_STD = "Philippines" if NAMES_STD == "840"
replace NAMES_STD = "Poland" if NAMES_STD == "290"
replace NAMES_STD = "Portugal" if NAMES_STD == "235"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "6"
replace NAMES_STD = "Qatar" if NAMES_STD == "694"
replace NAMES_STD = "Romania" if NAMES_STD == "360"
replace NAMES_STD = "Russia" if NAMES_STD == "365"
replace NAMES_STD = "Rwanda" if NAMES_STD == "517"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "60"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "56"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "57"
replace NAMES_STD = "San Marino" if NAMES_STD == "331"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "403"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "670"
replace NAMES_STD = "Saxony" if NAMES_STD == "269"
replace NAMES_STD = "Senegal" if NAMES_STD == "433"
replace NAMES_STD = "Seychelles" if NAMES_STD == "591"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "451"
replace NAMES_STD = "Singapore" if NAMES_STD == "830"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "317"
replace NAMES_STD = "Slovenia" if NAMES_STD == "349"
replace NAMES_STD = "Solomon Islands" if NAMES_STD == "940"
replace NAMES_STD = "Somalia" if NAMES_STD == "520"
replace NAMES_STD = "South Africa" if NAMES_STD == "560"
replace NAMES_STD = "Spain" if NAMES_STD == "230"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "780"
replace NAMES_STD = "Sudan" if NAMES_STD == "625"
replace NAMES_STD = "Suriname" if NAMES_STD == "115"
replace NAMES_STD = "Swaziland" if NAMES_STD == "572"
replace NAMES_STD = "Sweden" if NAMES_STD == "380"
replace NAMES_STD = "Switzerland" if NAMES_STD == "225"
replace NAMES_STD = "Syria" if NAMES_STD == "652"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "702"
replace NAMES_STD = "Taiwan" if NAMES_STD == "713"
replace NAMES_STD = "Tanzania" if NAMES_STD == "510"
replace NAMES_STD = "Thailand" if NAMES_STD == "800"
replace NAMES_STD = "Togo" if NAMES_STD == "461"
replace NAMES_STD = "Tonga" if NAMES_STD == "955"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "52"
replace NAMES_STD = "Tunisia" if NAMES_STD == "616"
replace NAMES_STD = "Turkey" if NAMES_STD == "640"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "701"
replace NAMES_STD = "Tuscany" if NAMES_STD == "337"
replace NAMES_STD = "Tuvalu" if NAMES_STD == "947"
replace NAMES_STD = "Two Sicilies" if NAMES_STD == "329"
replace NAMES_STD = "Uganda" if NAMES_STD == "500"
replace NAMES_STD = "Ukraine" if NAMES_STD == "369"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "696"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "200"
replace NAMES_STD = "United States" if NAMES_STD == "2"
replace NAMES_STD = "Uruguay" if NAMES_STD == "165"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "704"
replace NAMES_STD = "Vanuatu" if NAMES_STD == "935"
replace NAMES_STD = "Vatican" if NAMES_STD == "327"
replace NAMES_STD = "Venezuela" if NAMES_STD == "101"
replace NAMES_STD = "Vietnam" if NAMES_STD == "816"
replace NAMES_STD = "Republic of Vietnam" if NAMES_STD == "817"
replace NAMES_STD = "Samoa" if NAMES_STD == "990"
replace NAMES_STD = "Wuerttemburg" if NAMES_STD == "271"
replace NAMES_STD = "Yemen" if NAMES_STD == "679"
replace NAMES_STD = "Yemen Arab Republic" if NAMES_STD == "678"
replace NAMES_STD = "Yemen People's Republic" if NAMES_STD == "680"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "345"
replace NAMES_STD = "Zambia" if NAMES_STD == "551"
replace NAMES_STD = "Zanzibar" if NAMES_STD == "511"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "552"

end 
exit
