/***** IMF codes *****/

program k_imfn
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "512"
replace NAMES_STD = "Albania" if NAMES_STD == "914"
replace NAMES_STD = "Algeria" if NAMES_STD == "612"
replace NAMES_STD = "American Samoa" if NAMES_STD == "859"
replace NAMES_STD = "Angola" if NAMES_STD == "614"
replace NAMES_STD = "Anguilla" if NAMES_STD == "312"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "311"
replace NAMES_STD = "Argentina" if NAMES_STD == "213"
replace NAMES_STD = "Armenia" if NAMES_STD == "911"
replace NAMES_STD = "Aruba" if NAMES_STD == "314"
replace NAMES_STD = "Australia" if NAMES_STD == "193"
replace NAMES_STD = "Austria" if NAMES_STD == "122"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "912"
replace NAMES_STD = "Bahamas" if NAMES_STD == "313"
replace NAMES_STD = "Bahrain" if NAMES_STD == "419"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "513"
replace NAMES_STD = "Barbados" if NAMES_STD == "316"
replace NAMES_STD = "Belarus" if NAMES_STD == "913"
replace NAMES_STD = "Belgium" if NAMES_STD == "124"
replace NAMES_STD = "Belgium-Luxembourg" if NAMES_STD == "124"
replace NAMES_STD = "Belize" if NAMES_STD == "339"
replace NAMES_STD = "Benin" if NAMES_STD == "638"
replace NAMES_STD = "Bermuda" if NAMES_STD == "319"
replace NAMES_STD = "Bhutan" if NAMES_STD == "514"
replace NAMES_STD = "Bolivia" if NAMES_STD == "218"
replace NAMES_STD = "Bosnia and Herzegovina" if NAMES_STD == "963"
replace NAMES_STD = "Botswana" if NAMES_STD == "616"
replace NAMES_STD = "Brazil" if NAMES_STD == "223"
replace NAMES_STD = "Brunei" if NAMES_STD == "516"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "918"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "748"
replace NAMES_STD = "Burundi" if NAMES_STD == "618"
replace NAMES_STD = "Cambodia" if NAMES_STD == "522"
replace NAMES_STD = "Cameroon" if NAMES_STD == "622"
replace NAMES_STD = "Canada" if NAMES_STD == "156"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "624"
replace NAMES_STD = "Cayman Islands" if NAMES_STD == "377"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "626"
replace NAMES_STD = "Chad" if NAMES_STD == "628"
replace NAMES_STD = "Chile" if NAMES_STD == "228"
replace NAMES_STD = "China" if NAMES_STD == "924"
replace NAMES_STD = "Colombia" if NAMES_STD == "233"
replace NAMES_STD = "Comoros" if NAMES_STD == "632"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "636"
replace NAMES_STD = "Congo" if NAMES_STD == "634"
replace NAMES_STD = "Cook Islands" if NAMES_STD == "815"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "238"
replace NAMES_STD = "Croatia" if NAMES_STD == "960"
replace NAMES_STD = "Cuba" if NAMES_STD == "928"
replace NAMES_STD = "Cyprus" if NAMES_STD == "423"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "935"
replace NAMES_STD = "Czechoslovakia" if NAMES_STD == "934"
replace NAMES_STD = "Denmark" if NAMES_STD == "128"
replace NAMES_STD = "Djibouti" if NAMES_STD == "611"
replace NAMES_STD = "Dominica" if NAMES_STD == "321"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "243"
replace NAMES_STD = "Ecuador" if NAMES_STD == "248"
replace NAMES_STD = "Egypt" if NAMES_STD == "469"
replace NAMES_STD = "El Salvador" if NAMES_STD == "253"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "642"
replace NAMES_STD = "Eritrea" if NAMES_STD == "643"
replace NAMES_STD = "Estonia" if NAMES_STD == "939"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "644"
replace NAMES_STD = "Faeroe Islands" if NAMES_STD == "816"
replace NAMES_STD = "Falkland Islands" if NAMES_STD == "323"
replace NAMES_STD = "Fiji" if NAMES_STD == "819"
replace NAMES_STD = "Finland" if NAMES_STD == "172"
replace NAMES_STD = "France" if NAMES_STD == "132"
replace NAMES_STD = "French Polynesia" if NAMES_STD == "887"
replace NAMES_STD = "Gabon" if NAMES_STD == "646"
replace NAMES_STD = "Gambia" if NAMES_STD == "648"
replace NAMES_STD = "Georgia" if NAMES_STD == "915"
replace NAMES_STD = "German Democratic Republic" if NAMES_STD == "938"
replace NAMES_STD = "Germany" if NAMES_STD == "134"
replace NAMES_STD = "Ghana" if NAMES_STD == "652"
replace NAMES_STD = "Gibraltar" if NAMES_STD == "823"
replace NAMES_STD = "Greece" if NAMES_STD == "174"
replace NAMES_STD = "Greenland" if NAMES_STD == "326"
replace NAMES_STD = "Grenada" if NAMES_STD == "328"
replace NAMES_STD = "Guadeloupe" if NAMES_STD == "329"
replace NAMES_STD = "Guam" if NAMES_STD == "829"
replace NAMES_STD = "Guatemala" if NAMES_STD == "258"
replace NAMES_STD = "Guinea" if NAMES_STD == "656"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "654"
replace NAMES_STD = "Guyana" if NAMES_STD == "336"
replace NAMES_STD = "French Guiana" if NAMES_STD == "333"
replace NAMES_STD = "Haiti" if NAMES_STD == "263"
replace NAMES_STD = "Honduras" if NAMES_STD == "268"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "532"
replace NAMES_STD = "Hungary" if NAMES_STD == "944"
replace NAMES_STD = "Iceland" if NAMES_STD == "176"
replace NAMES_STD = "India" if NAMES_STD == "534"
replace NAMES_STD = "Indonesia" if NAMES_STD == "536"
replace NAMES_STD = "Iran" if NAMES_STD == "429"
replace NAMES_STD = "Iraq" if NAMES_STD == "433"
replace NAMES_STD = "Ireland" if NAMES_STD == "178"
replace NAMES_STD = "Israel" if NAMES_STD == "436"
replace NAMES_STD = "Italy" if NAMES_STD == "136"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "662"
replace NAMES_STD = "Jamaica" if NAMES_STD == "343"
replace NAMES_STD = "Japan" if NAMES_STD == "158"
replace NAMES_STD = "Jordan" if NAMES_STD == "439"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "916"
replace NAMES_STD = "Kenya" if NAMES_STD == "664"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "917"
replace NAMES_STD = "Kiribati" if NAMES_STD == "826"
replace NAMES_STD = "South Korea" if NAMES_STD == "542"
replace NAMES_STD = "North Korea" if NAMES_STD == "954"
replace NAMES_STD = "Kuwait" if NAMES_STD == "443"
replace NAMES_STD = "Laos" if NAMES_STD == "544"
replace NAMES_STD = "Latvia" if NAMES_STD == "941"
replace NAMES_STD = "Lebanon" if NAMES_STD == "446"
replace NAMES_STD = "Leeward Islands" if NAMES_STD == "346"
replace NAMES_STD = "Lesotho" if NAMES_STD == "666"
replace NAMES_STD = "Liberia" if NAMES_STD == "668"
replace NAMES_STD = "Libya" if NAMES_STD == "672"
replace NAMES_STD = "Lithuania" if NAMES_STD == "946"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "137"
replace NAMES_STD = "Macao" if NAMES_STD == "546"
replace NAMES_STD = "Macedonia" if NAMES_STD == "962"
replace NAMES_STD = "Madagascar" if NAMES_STD == "674"
replace NAMES_STD = "Malawi" if NAMES_STD == "676"
replace NAMES_STD = "Malaysia" if NAMES_STD == "548"
replace NAMES_STD = "Maldives" if NAMES_STD == "556"
replace NAMES_STD = "Mali" if NAMES_STD == "678"
replace NAMES_STD = "Malta" if NAMES_STD == "181"
replace NAMES_STD = "Marshall Islands" if NAMES_STD == "867"
replace NAMES_STD = "Martinique" if NAMES_STD == "349"
replace NAMES_STD = "Mauritania" if NAMES_STD == "682"
replace NAMES_STD = "Mauritius" if NAMES_STD == "684"
replace NAMES_STD = "Mexico" if NAMES_STD == "273"
replace NAMES_STD = "Micronesia" if NAMES_STD == "868"
replace NAMES_STD = "Moldova" if NAMES_STD == "921"
replace NAMES_STD = "Mongolia" if NAMES_STD == "948"
replace NAMES_STD = "Montenegro" if NAMES_STD == "943"
replace NAMES_STD = "Montserrat" if NAMES_STD == "351"
replace NAMES_STD = "Morocco" if NAMES_STD == "686"
replace NAMES_STD = "Mozambique" if NAMES_STD == "688"
replace NAMES_STD = "Myanmar" if NAMES_STD == "518"
replace NAMES_STD = "Namibia" if NAMES_STD == "728"
replace NAMES_STD = "Nauru" if NAMES_STD == "836"
replace NAMES_STD = "Nepal" if NAMES_STD == "558"
replace NAMES_STD = "Netherlands" if NAMES_STD == "138"
replace NAMES_STD = "Netherlands Antilles" if NAMES_STD == "353"
replace NAMES_STD = "New Caledonia" if NAMES_STD == "839"
replace NAMES_STD = "New Zealand" if NAMES_STD == "196"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "278"
replace NAMES_STD = "Niger" if NAMES_STD == "692"
replace NAMES_STD = "Nigeria" if NAMES_STD == "694"
replace NAMES_STD = "Norway" if NAMES_STD == "142"
replace NAMES_STD = "Oman" if NAMES_STD == "449"
replace NAMES_STD = "Pakistan" if NAMES_STD == "564"
replace NAMES_STD = "Palau" if NAMES_STD == "565"
replace NAMES_STD = "Panama" if NAMES_STD == "283"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "853"
replace NAMES_STD = "Paraguay" if NAMES_STD == "288"
replace NAMES_STD = "Peru" if NAMES_STD == "293"
replace NAMES_STD = "Philippines" if NAMES_STD == "566"
replace NAMES_STD = "Poland" if NAMES_STD == "964"
replace NAMES_STD = "Portugal" if NAMES_STD == "182"
replace NAMES_STD = "Qatar" if NAMES_STD == "453"
replace NAMES_STD = "Reunion" if NAMES_STD == "696"
replace NAMES_STD = "Romania" if NAMES_STD == "968"
replace NAMES_STD = "Russia" if NAMES_STD == "922"
replace NAMES_STD = "Rwanda" if NAMES_STD == "714"
replace NAMES_STD = "Saint Helena" if NAMES_STD == "856"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "361"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "362"
replace NAMES_STD = "Saint Pierre and Miquelon" if NAMES_STD == "363"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "364"
replace NAMES_STD = "San Marino" if NAMES_STD == "135"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "716"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "456"
replace NAMES_STD = "Senegal" if NAMES_STD == "722"
replace NAMES_STD = "Seychelles" if NAMES_STD == "718"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "724"
replace NAMES_STD = "Singapore" if NAMES_STD == "576"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "936"
replace NAMES_STD = "Slovenia" if NAMES_STD == "961"
replace NAMES_STD = "Solomon Islands" if NAMES_STD == "813"
replace NAMES_STD = "Somalia" if NAMES_STD == "726"
replace NAMES_STD = "South Africa" if NAMES_STD == "199"
replace NAMES_STD = "Spain" if NAMES_STD == "184"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "524"
replace NAMES_STD = "Sudan" if NAMES_STD == "732"
replace NAMES_STD = "Suriname" if NAMES_STD == "366"
replace NAMES_STD = "Swaziland" if NAMES_STD == "734"
replace NAMES_STD = "Sweden" if NAMES_STD == "144"
replace NAMES_STD = "Switzerland" if NAMES_STD == "146"
replace NAMES_STD = "Syria" if NAMES_STD == "463"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "923"
replace NAMES_STD = "Taiwan" if NAMES_STD == "528"
replace NAMES_STD = "Tanzania" if NAMES_STD == "738"
replace NAMES_STD = "Thailand" if NAMES_STD == "578"
replace NAMES_STD = "Timor" if NAMES_STD == "537"
replace NAMES_STD = "Togo" if NAMES_STD == "742"
replace NAMES_STD = "Tonga" if NAMES_STD == "866"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "369"
replace NAMES_STD = "Tunisia" if NAMES_STD == "744"
replace NAMES_STD = "Turkey" if NAMES_STD == "186"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "925"
replace NAMES_STD = "Tuvalu" if NAMES_STD == "869"
replace NAMES_STD = "Uganda" if NAMES_STD == "746"
replace NAMES_STD = "Ukraine" if NAMES_STD == "926"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "466"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "112"
replace NAMES_STD = "United States" if NAMES_STD == "111"
replace NAMES_STD = "Uruguay" if NAMES_STD == "298"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "927"
replace NAMES_STD = "Vanuatu" if NAMES_STD == "846"
replace NAMES_STD = "Venezuela" if NAMES_STD == "299"
replace NAMES_STD = "Vietnam" if NAMES_STD == "582"
replace NAMES_STD = "United States Virgin Islands" if NAMES_STD == "373"
replace NAMES_STD = "Samoa" if NAMES_STD == "862"
replace NAMES_STD = "Yemen" if NAMES_STD == "473"
replace NAMES_STD = "Yemen Arab Republic" if NAMES_STD == "474"
replace NAMES_STD = "Yemen People's Republic" if NAMES_STD == "459"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "188"
replace NAMES_STD = "Zambia" if NAMES_STD == "754"
replace NAMES_STD = "Zanzibar" if NAMES_STD == "756"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "698"

end
exit
