/***** ISO 3166 codes, alpha-3 *****/

program k_iso3c
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "afg"
replace NAMES_STD = "Albania" if NAMES_STD == "alb"
replace NAMES_STD = "Algeria" if NAMES_STD == "dza"
replace NAMES_STD = "American Samoa" if NAMES_STD == "asm"
replace NAMES_STD = "Andorra" if NAMES_STD == "and" | NAMES_STD == "ado"
replace NAMES_STD = "Angola" if NAMES_STD == "ago"
replace NAMES_STD = "Anguilla" if NAMES_STD == "aia" | NAMES_STD == "kna2"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "atg"
replace NAMES_STD = "Argentina" if NAMES_STD == "arg"
replace NAMES_STD = "Armenia" if NAMES_STD == "arm"
replace NAMES_STD = "Aruba" if NAMES_STD == "abw"
replace NAMES_STD = "Australia" if NAMES_STD == "aus"
replace NAMES_STD = "Austria" if NAMES_STD == "aut"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "aze"
replace NAMES_STD = "Bahamas" if NAMES_STD == "bhs"
replace NAMES_STD = "Bahrain" if NAMES_STD == "bhr"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "bgd"
replace NAMES_STD = "Barbados" if NAMES_STD == "brb"
replace NAMES_STD = "Belarus" if NAMES_STD == "blr"
replace NAMES_STD = "Belgium" if NAMES_STD == "bel"
replace NAMES_STD = "Belize" if NAMES_STD == "blz"
replace NAMES_STD = "Benin" if NAMES_STD == "ben"
replace NAMES_STD = "Bermuda" if NAMES_STD == "bmu"
replace NAMES_STD = "Bhutan" if NAMES_STD == "btn"
replace NAMES_STD = "Bolivia" if NAMES_STD == "bol"
replace NAMES_STD = "Bosnia and Herzegovina" if NAMES_STD == "bih"
replace NAMES_STD = "Botswana" if NAMES_STD == "bwa"
replace NAMES_STD = "Brazil" if NAMES_STD == "bra"
replace NAMES_STD = "British Virgin Islands" if NAMES_STD == "vgb" | NAMES_STD == "bgv"
replace NAMES_STD = "Brunei" if NAMES_STD == "brn"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "bgr"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "bfa"
replace NAMES_STD = "Burundi" if NAMES_STD == "bdi"
replace NAMES_STD = "Cambodia" if NAMES_STD == "khm"
replace NAMES_STD = "Cameroon" if NAMES_STD == "cmr"
replace NAMES_STD = "Canada" if NAMES_STD == "can"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "cpv"
replace NAMES_STD = "Cayman Islands" if NAMES_STD == "cym"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "caf"
replace NAMES_STD = "Chad" if NAMES_STD == "tcd"
replace NAMES_STD = "Chile" if NAMES_STD == "chl"
replace NAMES_STD = "China" if NAMES_STD == "chn"
replace NAMES_STD = "Christmas Islands" if NAMES_STD == "cxr"
replace NAMES_STD = "Cocos Islands" if NAMES_STD == "cck"
replace NAMES_STD = "Colombia" if NAMES_STD == "col"
replace NAMES_STD = "Comoros" if NAMES_STD == "com"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "cod" | NAMES_STD == "zar"
replace NAMES_STD = "Congo" if NAMES_STD == "cog"
replace NAMES_STD = "Cook Islands" if NAMES_STD == "cok"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "cri"
replace NAMES_STD = "Cuba" if NAMES_STD == "cub"
replace NAMES_STD = "Croatia" if NAMES_STD == "hrv"
replace NAMES_STD = "Cyprus" if NAMES_STD == "cyp"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "cze"
replace NAMES_STD = "Denmark" if NAMES_STD == "dnk"
replace NAMES_STD = "Djibouti" if NAMES_STD == "dji"
replace NAMES_STD = "Dominica" if NAMES_STD == "dma"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "dom"
replace NAMES_STD = "Ecuador" if NAMES_STD == "ecu"
replace NAMES_STD = "Egypt" if NAMES_STD == "egy"
replace NAMES_STD = "El Salvador" if NAMES_STD == "slv"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "gnq"
replace NAMES_STD = "Eritrea" if NAMES_STD == "eri"
replace NAMES_STD = "Estonia" if NAMES_STD == "est"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "eth"
//replace NAMES_STD = "European Union" if NAMES_STD == "eu"
replace NAMES_STD = "Falkland Islands" if NAMES_STD == "flk"
replace NAMES_STD = "Faeroe Islands" if NAMES_STD == "fro"
replace NAMES_STD = "Fiji" if NAMES_STD == "fji"
replace NAMES_STD = "Finland" if NAMES_STD == "fin"
replace NAMES_STD = "France" if NAMES_STD == "fra"
replace NAMES_STD = "French Guiana" if NAMES_STD == "guf"
replace NAMES_STD = "French Polynesia" if NAMES_STD == "pyf"
replace NAMES_STD = "Gabon" if NAMES_STD == "gab"
replace NAMES_STD = "Gambia" if NAMES_STD == "gmb"
replace NAMES_STD = "Georgia" if NAMES_STD == "geo"
replace NAMES_STD = "Germany" if NAMES_STD == "deu" | NAMES_STD == "ger" 
replace NAMES_STD = "Ghana" if NAMES_STD == "gha"
replace NAMES_STD = "Gibraltar" if NAMES_STD == "gib"
replace NAMES_STD = "Greece" if NAMES_STD == "grc"
replace NAMES_STD = "Greenland" if NAMES_STD == "grl"
replace NAMES_STD = "Grenada" if NAMES_STD == "grd"
replace NAMES_STD = "Guadeloupe" if NAMES_STD == "glp"
replace NAMES_STD = "Guam" if NAMES_STD == "gum"
replace NAMES_STD = "Guatemala" if NAMES_STD == "gtm"
replace NAMES_STD = "Guinea" if NAMES_STD == "gin"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "gnb"
replace NAMES_STD = "Guyana" if NAMES_STD == "guy"
replace NAMES_STD = "Haiti" if NAMES_STD == "hti"
replace NAMES_STD = "Honduras" if NAMES_STD == "hnd"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "hkg"
replace NAMES_STD = "Hungary" if NAMES_STD == "hun"
replace NAMES_STD = "Iceland" if NAMES_STD == "isl"
replace NAMES_STD = "India" if NAMES_STD == "ind"
replace NAMES_STD = "Indonesia" if NAMES_STD == "idn"
replace NAMES_STD = "Iran" if NAMES_STD == "irn"
replace NAMES_STD = "Iraq" if NAMES_STD == "irq"
replace NAMES_STD = "Ireland" if NAMES_STD == "irl"
replace NAMES_STD = "Israel" if NAMES_STD == "isr"
replace NAMES_STD = "Italy" if NAMES_STD == "ita"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "civ"
replace NAMES_STD = "Jamaica" if NAMES_STD == "jam"
replace NAMES_STD = "Japan" if NAMES_STD == "jpn"
replace NAMES_STD = "Jordan" if NAMES_STD == "jor"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "kaz"
replace NAMES_STD = "Kenya" if NAMES_STD == "ken"
replace NAMES_STD = "Kiribati" if NAMES_STD == "kir"
replace NAMES_STD = "South Korea" if NAMES_STD == "kor"
replace NAMES_STD = "North Korea" if NAMES_STD == "prk"
replace NAMES_STD = "Kuwait" if NAMES_STD == "kwt"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "kgz"
replace NAMES_STD = "Laos" if NAMES_STD == "lao"
replace NAMES_STD = "Latvia" if NAMES_STD == "lva"
replace NAMES_STD = "Lebanon" if NAMES_STD == "lbn"
replace NAMES_STD = "Lesotho" if NAMES_STD == "lso"
replace NAMES_STD = "Liberia" if NAMES_STD == "lbr"
replace NAMES_STD = "Libya" if NAMES_STD == "lby"
replace NAMES_STD = "Liechtenstein" if NAMES_STD == "lie"
replace NAMES_STD = "Lithuania" if NAMES_STD == "ltu"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "lux"
replace NAMES_STD = "Macao" if NAMES_STD == "mac"
replace NAMES_STD = "Macedonia" if NAMES_STD == "mkd"
replace NAMES_STD = "Madagascar" if NAMES_STD == "mdg"
replace NAMES_STD = "Malawi" if NAMES_STD == "mwi"
replace NAMES_STD = "Malaysia" if NAMES_STD == "mys"
replace NAMES_STD = "Maldives" if NAMES_STD == "mdv"
replace NAMES_STD = "Mali" if NAMES_STD == "mli"
replace NAMES_STD = "Malta" if NAMES_STD == "mlt"
replace NAMES_STD = "Marshall Islands" if NAMES_STD == "mhl"
replace NAMES_STD = "Martinique" if NAMES_STD == "mtq"
replace NAMES_STD = "Mauritania" if NAMES_STD == "mrt"
replace NAMES_STD = "Mauritius" if NAMES_STD == "mus"
replace NAMES_STD = "Mayotte" if NAMES_STD == "myt"
replace NAMES_STD = "Mexico" if NAMES_STD == "mex"
replace NAMES_STD = "Micronesia" if NAMES_STD == "fsm"
replace NAMES_STD = "Moldova" if NAMES_STD == "mda"
replace NAMES_STD = "Monaco" if NAMES_STD == "mco"
replace NAMES_STD = "Mongolia" if NAMES_STD == "mng"
replace NAMES_STD = "Montenegro" if NAMES_STD == "mne"
replace NAMES_STD = "Montserrat" if NAMES_STD == "msr"
replace NAMES_STD = "Morocco" if NAMES_STD == "mar"
replace NAMES_STD = "Mozambique" if NAMES_STD == "moz"
replace NAMES_STD = "Myanmar" if NAMES_STD == "mmr"
replace NAMES_STD = "Namibia" if NAMES_STD == "nam"
replace NAMES_STD = "Nauru" if NAMES_STD == "nru"
replace NAMES_STD = "Nepal" if NAMES_STD == "npl"
replace NAMES_STD = "Netherlands" if NAMES_STD == "nld"
replace NAMES_STD = "Netherlands Antilles" if NAMES_STD == "ant"
replace NAMES_STD = "New Caledonia" if NAMES_STD == "ncl"
replace NAMES_STD = "New Zealand" if NAMES_STD == "nzl"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "nic"
replace NAMES_STD = "Niger" if NAMES_STD == "ner"
replace NAMES_STD = "Nigeria" if NAMES_STD == "nga"
replace NAMES_STD = "Niue" if NAMES_STD == "niu"
replace NAMES_STD = "Norway" if NAMES_STD == "nor"
replace NAMES_STD = "Oman" if NAMES_STD == "omn"
replace NAMES_STD = "Pakistan" if NAMES_STD == "pak"
replace NAMES_STD = "Palau" if NAMES_STD == "plw"
replace NAMES_STD = "Palestine" if NAMES_STD == "pse" | NAMES_STD == "wbg"
replace NAMES_STD = "Panama" if NAMES_STD == "pan"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "png"
replace NAMES_STD = "Paraguay" if NAMES_STD == "pry"
replace NAMES_STD = "Peru" if NAMES_STD == "per"
replace NAMES_STD = "Philippines" if NAMES_STD == "phl"
replace NAMES_STD = "Poland" if NAMES_STD == "pol"
replace NAMES_STD = "Portugal" if NAMES_STD == "prt"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "pri"
replace NAMES_STD = "Qatar" if NAMES_STD == "qat"
replace NAMES_STD = "Reunion" if NAMES_STD == "reu"
replace NAMES_STD = "Romania" if NAMES_STD == "rou" | NAMES_STD == "rom"
replace NAMES_STD = "Russia" if NAMES_STD == "rus"
replace NAMES_STD = "Rwanda" if NAMES_STD == "rwa"
replace NAMES_STD = "Saint Helena" if NAMES_STD == "shn"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "kna"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "lca"
replace NAMES_STD = "Saint Pierre and Miquelon" if NAMES_STD == "spm"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "vct"
replace NAMES_STD = "Samoa" if NAMES_STD == "wsm"
replace NAMES_STD = "San Marino" if NAMES_STD == "smr"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "stp"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "sau"
replace NAMES_STD = "Senegal" if NAMES_STD == "sen"
replace NAMES_STD = "Seychelles" if NAMES_STD == "syc"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "sle"
replace NAMES_STD = "Singapore" if NAMES_STD == "sgp"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "svk"
replace NAMES_STD = "Slovenia" if NAMES_STD == "svn"
replace NAMES_STD = "Solomon Islands" if NAMES_STD == "slb"
replace NAMES_STD = "Somalia" if NAMES_STD == "som"
replace NAMES_STD = "South Africa" if NAMES_STD == "zaf"
replace NAMES_STD = "Spain" if NAMES_STD == "esp"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "lka"
replace NAMES_STD = "Sudan" if NAMES_STD == "sdn"
replace NAMES_STD = "South Sudan" if NAMES_STD == "ssd"
replace NAMES_STD = "Suriname" if NAMES_STD == "sur"
replace NAMES_STD = "Swaziland" if NAMES_STD == "swz"
replace NAMES_STD = "Sweden" if NAMES_STD == "swe"
replace NAMES_STD = "Switzerland" if NAMES_STD == "che"
replace NAMES_STD = "Syria" if NAMES_STD == "syr"
replace NAMES_STD = "Taiwan" if NAMES_STD == "twn"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "tjk"
replace NAMES_STD = "Tanzania" if NAMES_STD == "tza"
replace NAMES_STD = "Thailand" if NAMES_STD == "tha"
replace NAMES_STD = "Timor" if NAMES_STD == "tls"
replace NAMES_STD = "Togo" if NAMES_STD == "tgo"
replace NAMES_STD = "Tonga" if NAMES_STD == "ton"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "tto"
replace NAMES_STD = "Tunisia" if NAMES_STD == "tun"
replace NAMES_STD = "Turkey" if NAMES_STD == "tur"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "tkm"
replace NAMES_STD = "Turks and Caicos Islands" if NAMES_STD == "tca"
replace NAMES_STD = "Tuvalu" if NAMES_STD == "tuv"
replace NAMES_STD = "Uganda" if NAMES_STD == "uga"
replace NAMES_STD = "Ukraine" if NAMES_STD == "ukr"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "are"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "gbr"
replace NAMES_STD = "United States" if NAMES_STD == "usa"
replace NAMES_STD = "United States Virgin Islands" if NAMES_STD == "vir"
replace NAMES_STD = "Uruguay" if NAMES_STD == "ury"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "uzb"
replace NAMES_STD = "Vanuatu" if NAMES_STD == "vut"
replace NAMES_STD = "Vatican" if NAMES_STD == "vat"
replace NAMES_STD = "Venezuela" if NAMES_STD == "ven"
replace NAMES_STD = "Vietnam" if NAMES_STD == "vnm"
replace NAMES_STD = "Wallis and Futuna" if NAMES_STD == "wlf"
replace NAMES_STD = "Western Sahara" if NAMES_STD == "esh"
replace NAMES_STD = "Yemen" if NAMES_STD == "yem"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "srb" | NAMES_STD == "yug"
replace NAMES_STD = "Zambia" if NAMES_STD == "zmb"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "zwe"

end
exit
