/***** United Nations Statistics Division codes, same as ISO 3166 numeric *****/

/*** Note: UN Stats codes are always 3-digit codes, e.g.
Albania is not 8 but 008, Algeria is not 12 but 012, etc.
Here, the leading zeroes are dropped ***/

program k_iso3n
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "4"
replace NAMES_STD = "Albania" if NAMES_STD == "8"
replace NAMES_STD = "Algeria" if NAMES_STD == "12"
replace NAMES_STD = "American Samoa" if NAMES_STD == "16"
replace NAMES_STD = "Andorra" if NAMES_STD == "20"
replace NAMES_STD = "Angola" if NAMES_STD == "24"
replace NAMES_STD = "Anguilla" if NAMES_STD == "660"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "28"
replace NAMES_STD = "Argentina" if NAMES_STD == "32"
replace NAMES_STD = "Armenia" if NAMES_STD == "51"
replace NAMES_STD = "Aruba" if NAMES_STD == "533"
replace NAMES_STD = "Australia" if NAMES_STD == "36"
replace NAMES_STD = "Austria" if NAMES_STD == "40"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "31"
replace NAMES_STD = "Bahamas" if NAMES_STD == "44"
replace NAMES_STD = "Bahrain" if NAMES_STD == "48"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "50"
replace NAMES_STD = "Barbados" if NAMES_STD == "52"
replace NAMES_STD = "Belarus" if NAMES_STD == "112"
replace NAMES_STD = "Belgium" if NAMES_STD == "56"
replace NAMES_STD = "Belgium-Luxembourg" if NAMES_STD == "58"
replace NAMES_STD = "Belize" if NAMES_STD == "84"
replace NAMES_STD = "Benin" if NAMES_STD == "204"
replace NAMES_STD = "Bermuda" if NAMES_STD == "60"
replace NAMES_STD = "Bhutan" if NAMES_STD == "64"
replace NAMES_STD = "Bolivia" if NAMES_STD == "68"
replace NAMES_STD = "Bonaire" if NAMES_STD == "534"
replace NAMES_STD = "Bosnia and Herzegovina" if NAMES_STD == "70"
replace NAMES_STD = "Botswana" if NAMES_STD == "72"
replace NAMES_STD = "Brazil" if NAMES_STD == "76"
replace NAMES_STD = "Brunei" if NAMES_STD == "96"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "100"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "854"
replace NAMES_STD = "Burundi" if NAMES_STD == "108"
replace NAMES_STD = "Cambodia" if NAMES_STD == "116"
replace NAMES_STD = "Cameroon" if NAMES_STD == "120"
replace NAMES_STD = "Canada" if NAMES_STD == "124"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "132"
replace NAMES_STD = "Cayman Islands" if NAMES_STD == "136"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "140"
replace NAMES_STD = "Chad" if NAMES_STD == "148"
replace NAMES_STD = "Channel Islands" if NAMES_STD == "830"
replace NAMES_STD = "Chile" if NAMES_STD == "152"
replace NAMES_STD = "China" if NAMES_STD == "156"
replace NAMES_STD = "Christmas Islands" if NAMES_STD == "162"
replace NAMES_STD = "Cocos Islands" if NAMES_STD == "166"
replace NAMES_STD = "Colombia" if NAMES_STD == "170"
replace NAMES_STD = "Comoros" if NAMES_STD == "174"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "180"
replace NAMES_STD = "Congo" if NAMES_STD == "178"
replace NAMES_STD = "Cook Islands" if NAMES_STD == "184"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "188"
replace NAMES_STD = "Croatia" if NAMES_STD == "191"
replace NAMES_STD = "Cuba" if NAMES_STD == "192"
replace NAMES_STD = "Curacao" if NAMES_STD == "535"
replace NAMES_STD = "Cyprus" if NAMES_STD == "196"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "203"
replace NAMES_STD = "Czechoslavakia" if NAMES_STD == "200"
replace NAMES_STD = "Denmark" if NAMES_STD == "208"
replace NAMES_STD = "Djibouti" if NAMES_STD == "262"
replace NAMES_STD = "Dominica" if NAMES_STD == "212"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "214"
replace NAMES_STD = "Ecuador" if NAMES_STD == "218"
replace NAMES_STD = "Egypt" if NAMES_STD == "818"
replace NAMES_STD = "El Salvador" if NAMES_STD == "222"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "226"
replace NAMES_STD = "Eritrea" if NAMES_STD == "232"
replace NAMES_STD = "Estonia" if NAMES_STD == "233"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "231"
replace NAMES_STD = "Faeroe Islands" if NAMES_STD == "234"
replace NAMES_STD = "Falkland Islands" if NAMES_STD == "238"
replace NAMES_STD = "Fiji" if NAMES_STD == "242"
replace NAMES_STD = "Finland" if NAMES_STD == "246"
replace NAMES_STD = "France" if NAMES_STD == "250"
replace NAMES_STD = "French Polynesia" if NAMES_STD == "258"
replace NAMES_STD = "Gabon" if NAMES_STD == "266"
replace NAMES_STD = "Gambia" if NAMES_STD == "270"
replace NAMES_STD = "Georgia" if NAMES_STD == "268"
replace NAMES_STD = "German Democratic Republic" if NAMES_STD == "278"
replace NAMES_STD = "Germany" if NAMES_STD == "276"
replace NAMES_STD = "Ghana" if NAMES_STD == "288"
replace NAMES_STD = "Gibraltar" if NAMES_STD == "292"
replace NAMES_STD = "Greece" if NAMES_STD == "300"
replace NAMES_STD = "Greenland" if NAMES_STD == "304"
replace NAMES_STD = "Grenada" if NAMES_STD == "308"
replace NAMES_STD = "Guadeloupe" if NAMES_STD == "312"
replace NAMES_STD = "Guam" if NAMES_STD == "316"
replace NAMES_STD = "Guatemala" if NAMES_STD == "320"
replace NAMES_STD = "Guinea" if NAMES_STD == "324"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "624"
replace NAMES_STD = "Guyana" if NAMES_STD == "328"
replace NAMES_STD = "French Guiana" if NAMES_STD == "254"
replace NAMES_STD = "Haiti" if NAMES_STD == "332"
replace NAMES_STD = "Honduras" if NAMES_STD == "340"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "344"
replace NAMES_STD = "Hungary" if NAMES_STD == "348"
replace NAMES_STD = "Iceland" if NAMES_STD == "352"
replace NAMES_STD = "India" if NAMES_STD == "356"
replace NAMES_STD = "Indonesia" if NAMES_STD == "360"
replace NAMES_STD = "Iran" if NAMES_STD == "364"
replace NAMES_STD = "Iraq" if NAMES_STD == "368"
replace NAMES_STD = "Ireland" if NAMES_STD == "372"
replace NAMES_STD = "Israel" if NAMES_STD == "376"
replace NAMES_STD = "Italy" if NAMES_STD == "380"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "384"
replace NAMES_STD = "Jamaica" if NAMES_STD == "388"
replace NAMES_STD = "Japan" if NAMES_STD == "392"
replace NAMES_STD = "Jordan" if NAMES_STD == "400"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "398"
replace NAMES_STD = "Kenya" if NAMES_STD == "404"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "417"
replace NAMES_STD = "Kiribati" if NAMES_STD == "296"
replace NAMES_STD = "South Korea" if NAMES_STD == "410"
replace NAMES_STD = "North Korea" if NAMES_STD == "408"
replace NAMES_STD = "Kuwait" if NAMES_STD == "414"
replace NAMES_STD = "Laos" if NAMES_STD == "418"
replace NAMES_STD = "Latvia" if NAMES_STD == "428"
replace NAMES_STD = "Lebanon" if NAMES_STD == "422"
replace NAMES_STD = "Lesotho" if NAMES_STD == "426"
replace NAMES_STD = "Liberia" if NAMES_STD == "430"
replace NAMES_STD = "Libya" if NAMES_STD == "434"
replace NAMES_STD = "Liechtenstein" if NAMES_STD == "438"
replace NAMES_STD = "Lithuania" if NAMES_STD == "440"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "442"
replace NAMES_STD = "Macao" if NAMES_STD == "446"
replace NAMES_STD = "Macedonia" if NAMES_STD == "807"
replace NAMES_STD = "Madagascar" if NAMES_STD == "450"
replace NAMES_STD = "Malawi" if NAMES_STD == "454"
replace NAMES_STD = "Malaysia" if NAMES_STD == "458"
replace NAMES_STD = "Maldives" if NAMES_STD == "462"
replace NAMES_STD = "Mali" if NAMES_STD == "466"
replace NAMES_STD = "Malta" if NAMES_STD == "470"
replace NAMES_STD = "Marshall Islands" if NAMES_STD == "584"
replace NAMES_STD = "Martinique" if NAMES_STD == "474"
replace NAMES_STD = "Mauritania" if NAMES_STD == "478"
replace NAMES_STD = "Mauritius" if NAMES_STD == "480"
replace NAMES_STD = "Mayotte" if NAMES_STD == "175"
replace NAMES_STD = "Mexico" if NAMES_STD == "484"
replace NAMES_STD = "Micronesia" if NAMES_STD == "583"
replace NAMES_STD = "Moldova" if NAMES_STD == "498"
replace NAMES_STD = "Monaco" if NAMES_STD == "492"
replace NAMES_STD = "Mongolia" if NAMES_STD == "496"
replace NAMES_STD = "Montenegro" if NAMES_STD == "499"
replace NAMES_STD = "Montserrat" if NAMES_STD == "500"
replace NAMES_STD = "Morocco" if NAMES_STD == "504"
replace NAMES_STD = "Mozambique" if NAMES_STD == "508"
replace NAMES_STD = "Myanmar" if NAMES_STD == "104"
replace NAMES_STD = "Namibia" if NAMES_STD == "516"
replace NAMES_STD = "Nauru" if NAMES_STD == "520"
replace NAMES_STD = "Nepal" if NAMES_STD == "524"
replace NAMES_STD = "Netherlands" if NAMES_STD == "528"
replace NAMES_STD = "Netherlands Antilles" if NAMES_STD == "530"
replace NAMES_STD = "New Caledonia" if NAMES_STD == "540"
replace NAMES_STD = "New Zealand" if NAMES_STD == "554"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "558"
replace NAMES_STD = "Niger" if NAMES_STD == "562"
replace NAMES_STD = "Nigeria" if NAMES_STD == "566"
replace NAMES_STD = "Niue" if NAMES_STD == "570"
replace NAMES_STD = "Norway" if NAMES_STD == "578"
replace NAMES_STD = "Oman" if NAMES_STD == "512"
replace NAMES_STD = "Pakistan" if NAMES_STD == "586"
replace NAMES_STD = "Palau" if NAMES_STD == "585"
replace NAMES_STD = "Palestine" if NAMES_STD == "275"
replace NAMES_STD = "Panama" if NAMES_STD == "591"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "598"
replace NAMES_STD = "Paraguay" if NAMES_STD == "600"
replace NAMES_STD = "Peru" if NAMES_STD == "604"
replace NAMES_STD = "Philippines" if NAMES_STD == "608"
replace NAMES_STD = "Poland" if NAMES_STD == "616"
replace NAMES_STD = "Portugal" if NAMES_STD == "620"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "630"
replace NAMES_STD = "Qatar" if NAMES_STD == "634"
replace NAMES_STD = "Reunion" if NAMES_STD == "638"
replace NAMES_STD = "Romania" if NAMES_STD == "642"
replace NAMES_STD = "Russia" if NAMES_STD == "643" | NAMES_STD =="810"
replace NAMES_STD = "Rwanda" if NAMES_STD == "646"
replace NAMES_STD = "Saint Helena" if NAMES_STD == "654"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "659"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "662"
replace NAMES_STD = "Saint Pierre and Miquelon" if NAMES_STD == "666"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "670"
replace NAMES_STD = "Samoa" if NAMES_STD == "882"
replace NAMES_STD = "San Marino" if NAMES_STD == "674"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "678"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "682"
replace NAMES_STD = "Senegal" if NAMES_STD == "686"
replace NAMES_STD = "Seychelles" if NAMES_STD == "690"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "694"
replace NAMES_STD = "Singapore" if NAMES_STD == "702"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "703"
replace NAMES_STD = "Slovenia" if NAMES_STD == "705"
replace NAMES_STD = "Solomon Islands" if NAMES_STD == "90"
replace NAMES_STD = "Somalia" if NAMES_STD == "706"
replace NAMES_STD = "South Africa" if NAMES_STD == "710"
replace NAMES_STD = "Spain" if NAMES_STD == "724"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "144"
replace NAMES_STD = "Sudan" if NAMES_STD == "736" | NAMES_STD == "729"
replace NAMES_STD = "South Sudan" if NAMES_STD == "728"
replace NAMES_STD = "Suriname" if NAMES_STD == "740"
replace NAMES_STD = "Swaziland" if NAMES_STD == "748"
replace NAMES_STD = "Sweden" if NAMES_STD == "752"
replace NAMES_STD = "Switzerland" if NAMES_STD == "756"
replace NAMES_STD = "Syria" if NAMES_STD == "760"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "762"
replace NAMES_STD = "Tanzania" if NAMES_STD == "834" | NAMES_STD =="835"
replace NAMES_STD = "Thailand" if NAMES_STD == "764"
replace NAMES_STD = "Timor" if NAMES_STD == "626"
replace NAMES_STD = "Togo" if NAMES_STD == "768"
replace NAMES_STD = "Tonga" if NAMES_STD == "776"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "780"
replace NAMES_STD = "Tunisia" if NAMES_STD == "788"
replace NAMES_STD = "Turkey" if NAMES_STD == "792"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "795"
replace NAMES_STD = "Turks and Caicos Islands" if NAMES_STD == "796"
replace NAMES_STD = "Tuvalu" if NAMES_STD == "798"
replace NAMES_STD = "Uganda" if NAMES_STD == "800"
replace NAMES_STD = "Ukraine" if NAMES_STD == "804"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "784"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "826"
replace NAMES_STD = "United States" if NAMES_STD == "840"
replace NAMES_STD = "Uruguay" if NAMES_STD == "858"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "860"
replace NAMES_STD = "Vanuatu" if NAMES_STD == "548"
replace NAMES_STD = "Vatican" if NAMES_STD == "336"
replace NAMES_STD = "Venezuela" if NAMES_STD == "862"
replace NAMES_STD = "Vietnam" if NAMES_STD == "704"
replace NAMES_STD = "Republic of Vietnam" if NAMES_STD == "868"
replace NAMES_STD = "British Virgin Islands" if NAMES_STD == "92"
replace NAMES_STD = "United States Virgin Islands" if NAMES_STD == "850"
replace NAMES_STD = "Wallis and Futuna" if NAMES_STD == "876"
replace NAMES_STD = "Western Sahara" if NAMES_STD == "732"
replace NAMES_STD = "Yemen" if NAMES_STD == "887"
replace NAMES_STD = "Yemen Arab Republic" if NAMES_STD == "886"
replace NAMES_STD = "Yemen People's Republic" if NAMES_STD == "720"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "890" | NAMES_STD =="891"
replace NAMES_STD = "Zambia" if NAMES_STD == "894"
replace NAMES_STD = "Zanzibar" if NAMES_STD == "836"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "716"

end
exit
