/***** ISO 3166 codes, alpha-2 *****/

program k_iso2c
version 8.2

replace NAMES_STD = "Afghanistan" if NAMES_STD == "af"
replace NAMES_STD = "Albania" if NAMES_STD == "al"
replace NAMES_STD = "Algeria" if NAMES_STD == "dz"
replace NAMES_STD = "American Samoa" if NAMES_STD == "as"
replace NAMES_STD = "Andorra" if NAMES_STD == "ad"
replace NAMES_STD = "Angola" if NAMES_STD == "ao"
replace NAMES_STD = "Anguilla" if NAMES_STD == "ai"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "ag"
replace NAMES_STD = "Argentina" if NAMES_STD == "ar"
replace NAMES_STD = "Armenia" if NAMES_STD == "am"
replace NAMES_STD = "Aruba" if NAMES_STD == "aw"
replace NAMES_STD = "Australia" if NAMES_STD == "au"
replace NAMES_STD = "Austria" if NAMES_STD == "at"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "az"
replace NAMES_STD = "Bahamas" if NAMES_STD == "bs"
replace NAMES_STD = "Bahrain" if NAMES_STD == "bh"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "bd"
replace NAMES_STD = "Barbados" if NAMES_STD == "bb"
replace NAMES_STD = "Belarus" if NAMES_STD == "by"
replace NAMES_STD = "Belgium" if NAMES_STD == "be"
replace NAMES_STD = "Belize" if NAMES_STD == "bz"
replace NAMES_STD = "Benin" if NAMES_STD == "bj"
replace NAMES_STD = "Bermuda" if NAMES_STD == "bm"
replace NAMES_STD = "Bhutan" if NAMES_STD == "bt"
replace NAMES_STD = "Bolivia" if NAMES_STD == "bo"
replace NAMES_STD = "Bosnia and Herzegovina" if NAMES_STD == "ba"
replace NAMES_STD = "Botswana" if NAMES_STD == "bw"
replace NAMES_STD = "Brazil" if NAMES_STD == "br"
replace NAMES_STD = "British Virgin Islands" if NAMES_STD == "vg"
replace NAMES_STD = "Brunei" if NAMES_STD == "bn"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "bg"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "bf"
replace NAMES_STD = "Burundi" if NAMES_STD == "bi"
replace NAMES_STD = "Cambodia" if NAMES_STD == "kh"
replace NAMES_STD = "Cameroon" if NAMES_STD == "cm"
replace NAMES_STD = "Canada" if NAMES_STD == "ca"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "cv"
replace NAMES_STD = "Cayman Islands" if NAMES_STD == "ky"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "cf"
replace NAMES_STD = "Chad" if NAMES_STD == "td"
replace NAMES_STD = "Chile" if NAMES_STD == "cl"
replace NAMES_STD = "China" if NAMES_STD == "cn"
replace NAMES_STD = "Christmas Islands" if NAMES_STD == "cx"
replace NAMES_STD = "Cocos Islands" if NAMES_STD == "cc"
replace NAMES_STD = "Colombia" if NAMES_STD == "co"
replace NAMES_STD = "Comoros" if NAMES_STD == "km"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "cd"
replace NAMES_STD = "Congo" if NAMES_STD == "cg"
replace NAMES_STD = "Cook Islands" if NAMES_STD == "ck"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "cr"
replace NAMES_STD = "Cuba" if NAMES_STD == "cu"
replace NAMES_STD = "Croatia" if NAMES_STD == "hr"
replace NAMES_STD = "Cyprus" if NAMES_STD == "cy"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "cz"
replace NAMES_STD = "Denmark" if NAMES_STD == "dk"
replace NAMES_STD = "Djibouti" if NAMES_STD == "dj"
replace NAMES_STD = "Dominica" if NAMES_STD == "dm"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "do"
replace NAMES_STD = "Ecuador" if NAMES_STD == "ec"
replace NAMES_STD = "Egypt" if NAMES_STD == "eg"
replace NAMES_STD = "El Salvador" if NAMES_STD == "sv"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "gq"
replace NAMES_STD = "Eritrea" if NAMES_STD == "er"
replace NAMES_STD = "Estonia" if NAMES_STD == "ee"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "et"
replace NAMES_STD = "European Union" if NAMES_STD == "eu"
replace NAMES_STD = "Falkland Islands" if NAMES_STD == "fk"
replace NAMES_STD = "Faeroe Islands" if NAMES_STD == "fo"
replace NAMES_STD = "Fiji" if NAMES_STD == "fj"
replace NAMES_STD = "Finland" if NAMES_STD == "fi"
replace NAMES_STD = "France" if NAMES_STD == "fr"
replace NAMES_STD = "French Guiana" if NAMES_STD == "gf"
replace NAMES_STD = "French Polynesia" if NAMES_STD == "pf"
replace NAMES_STD = "Gabon" if NAMES_STD == "ga"
replace NAMES_STD = "Gambia" if NAMES_STD == "gm"
replace NAMES_STD = "Georgia" if NAMES_STD == "ge"
replace NAMES_STD = "Germany" if NAMES_STD == "de"
replace NAMES_STD = "Ghana" if NAMES_STD == "gh"
replace NAMES_STD = "Gibraltar" if NAMES_STD == "gi"
replace NAMES_STD = "Greece" if NAMES_STD == "gr"
replace NAMES_STD = "Greenland" if NAMES_STD == "gl"
replace NAMES_STD = "Grenada" if NAMES_STD == "gd"
replace NAMES_STD = "Guadeloupe" if NAMES_STD == "gp"
replace NAMES_STD = "Guam" if NAMES_STD == "gu"
replace NAMES_STD = "Guatemala" if NAMES_STD == "gt"
replace NAMES_STD = "Guinea" if NAMES_STD == "gn"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "gw"
replace NAMES_STD = "Guyana" if NAMES_STD == "gy"
replace NAMES_STD = "Haiti" if NAMES_STD == "ht"
replace NAMES_STD = "Honduras" if NAMES_STD == "hn"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "hk"
replace NAMES_STD = "Hungary" if NAMES_STD == "hu"
replace NAMES_STD = "Iceland" if NAMES_STD == "is"
replace NAMES_STD = "India" if NAMES_STD == "in"
replace NAMES_STD = "Indonesia" if NAMES_STD == "id"
replace NAMES_STD = "Iran" if NAMES_STD == "ir"
replace NAMES_STD = "Iraq" if NAMES_STD == "iq"
replace NAMES_STD = "Ireland" if NAMES_STD == "ie"
replace NAMES_STD = "Israel" if NAMES_STD == "il"
replace NAMES_STD = "Italy" if NAMES_STD == "it"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "ci"
replace NAMES_STD = "Jamaica" if NAMES_STD == "jm"
replace NAMES_STD = "Japan" if NAMES_STD == "jp"
replace NAMES_STD = "Jordan" if NAMES_STD == "jo"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "kz"
replace NAMES_STD = "Kenya" if NAMES_STD == "ke"
replace NAMES_STD = "Kiribati" if NAMES_STD == "ki"
replace NAMES_STD = "South Korea" if NAMES_STD == "kr"
replace NAMES_STD = "North Korea" if NAMES_STD == "kp"
replace NAMES_STD = "Kuwait" if NAMES_STD == "kw"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "kg"
replace NAMES_STD = "Laos" if NAMES_STD == "la"
replace NAMES_STD = "Latvia" if NAMES_STD == "lv"
replace NAMES_STD = "Lebanon" if NAMES_STD == "lb"
replace NAMES_STD = "Lesotho" if NAMES_STD == "ls"
replace NAMES_STD = "Liberia" if NAMES_STD == "lr"
replace NAMES_STD = "Libya" if NAMES_STD == "ly"
replace NAMES_STD = "Liechtenstein" if NAMES_STD == "li"
replace NAMES_STD = "Lithuania" if NAMES_STD == "lt"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "lu"
replace NAMES_STD = "Macao" if NAMES_STD == "mo"
replace NAMES_STD = "Macedonia" if NAMES_STD == "mk"
replace NAMES_STD = "Madagascar" if NAMES_STD == "mg"
replace NAMES_STD = "Malawi" if NAMES_STD == "mw"
replace NAMES_STD = "Malaysia" if NAMES_STD == "my"
replace NAMES_STD = "Maldives" if NAMES_STD == "mv"
replace NAMES_STD = "Mali" if NAMES_STD == "ml"
replace NAMES_STD = "Malta" if NAMES_STD == "mt"
replace NAMES_STD = "Marshall Islands" if NAMES_STD == "mh"
replace NAMES_STD = "Martinique" if NAMES_STD == "mq"
replace NAMES_STD = "Mauritania" if NAMES_STD == "mr"
replace NAMES_STD = "Mauritius" if NAMES_STD == "mu"
replace NAMES_STD = "Mayotte" if NAMES_STD == "yt"
replace NAMES_STD = "Mexico" if NAMES_STD == "mx"
replace NAMES_STD = "Micronesia" if NAMES_STD == "fm"
replace NAMES_STD = "Moldova" if NAMES_STD == "md"
replace NAMES_STD = "Monaco" if NAMES_STD == "mc"
replace NAMES_STD = "Mongolia" if NAMES_STD == "mn"
replace NAMES_STD = "Montenegro" if NAMES_STD == "me"
replace NAMES_STD = "Montserrat" if NAMES_STD == "ms"
replace NAMES_STD = "Morocco" if NAMES_STD == "ma"
replace NAMES_STD = "Mozambique" if NAMES_STD == "mz"
replace NAMES_STD = "Myanmar" if NAMES_STD == "mm"
replace NAMES_STD = "Namibia" if NAMES_STD == "na"
replace NAMES_STD = "Nauru" if NAMES_STD == "nr"
replace NAMES_STD = "Nepal" if NAMES_STD == "np"
replace NAMES_STD = "Netherlands" if NAMES_STD == "nl"
replace NAMES_STD = "Netherlands Antilles" if NAMES_STD == "an"
replace NAMES_STD = "New Caledonia" if NAMES_STD == "nc"
replace NAMES_STD = "New Zealand" if NAMES_STD == "nz"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "ni"
replace NAMES_STD = "Niger" if NAMES_STD == "ne"
replace NAMES_STD = "Nigeria" if NAMES_STD == "ng"
replace NAMES_STD = "Niue" if NAMES_STD == "nu"
replace NAMES_STD = "Norway" if NAMES_STD == "no"
replace NAMES_STD = "Oman" if NAMES_STD == "om"
replace NAMES_STD = "Pakistan" if NAMES_STD == "pk"
replace NAMES_STD = "Palau" if NAMES_STD == "pw"
replace NAMES_STD = "Palestine" if NAMES_STD == "ps"
replace NAMES_STD = "Panama" if NAMES_STD == "pa"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "pg"
replace NAMES_STD = "Paraguay" if NAMES_STD == "py"
replace NAMES_STD = "Peru" if NAMES_STD == "pe"
replace NAMES_STD = "Philippines" if NAMES_STD == "ph"
replace NAMES_STD = "Poland" if NAMES_STD == "pl"
replace NAMES_STD = "Portugal" if NAMES_STD == "pt"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "pr"
replace NAMES_STD = "Qatar" if NAMES_STD == "qa"
replace NAMES_STD = "Reunion" if NAMES_STD == "re"
replace NAMES_STD = "Romania" if NAMES_STD == "ro"
replace NAMES_STD = "Russia" if NAMES_STD == "ru"
replace NAMES_STD = "Rwanda" if NAMES_STD == "rw"
replace NAMES_STD = "Saint Helena" if NAMES_STD == "sh"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "kn"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "lc"
replace NAMES_STD = "Saint Pierre and Miquelon" if NAMES_STD == "pm"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "vc"
replace NAMES_STD = "Samoa" if NAMES_STD == "ws"
replace NAMES_STD = "San Marino" if NAMES_STD == "sm"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "st"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "sa"
replace NAMES_STD = "Senegal" if NAMES_STD == "sn"
replace NAMES_STD = "Seychelles" if NAMES_STD == "sc"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "sl"
replace NAMES_STD = "Singapore" if NAMES_STD == "sg"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "sk"
replace NAMES_STD = "Slovenia" if NAMES_STD == "si"
replace NAMES_STD = "Solomon Islands" if NAMES_STD == "sb"
replace NAMES_STD = "Somalia" if NAMES_STD == "so"
replace NAMES_STD = "South Africa" if NAMES_STD == "za"
replace NAMES_STD = "Spain" if NAMES_STD == "es"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "lk"
replace NAMES_STD = "Sudan" if NAMES_STD == "sd"
replace NAMES_STD = "South Sudan" if NAMES_STD == "ss"
replace NAMES_STD = "Suriname" if NAMES_STD == "sr"
replace NAMES_STD = "Swaziland" if NAMES_STD == "sz"
replace NAMES_STD = "Sweden" if NAMES_STD == "se"
replace NAMES_STD = "Switzerland" if NAMES_STD == "ch"
replace NAMES_STD = "Syria" if NAMES_STD == "sy"
replace NAMES_STD = "Taiwan" if NAMES_STD == "tw"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "tj"
replace NAMES_STD = "Tanzania" if NAMES_STD == "tz"
replace NAMES_STD = "Thailand" if NAMES_STD == "th"
replace NAMES_STD = "Timor" if NAMES_STD == "tl"
replace NAMES_STD = "Togo" if NAMES_STD == "tg"
replace NAMES_STD = "Tonga" if NAMES_STD == "to"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "tt"
replace NAMES_STD = "Tunisia" if NAMES_STD == "tn"
replace NAMES_STD = "Turkey" if NAMES_STD == "tr"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "tm"
replace NAMES_STD = "Turks and Caicos Islands" if NAMES_STD == "tc"
replace NAMES_STD = "Tuvalu" if NAMES_STD == "tv"
replace NAMES_STD = "Uganda" if NAMES_STD == "ug"
replace NAMES_STD = "Ukraine" if NAMES_STD == "ua"
replace NAMES_STD = "United Arab Emirates" if NAMES_STD == "ue"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "uk" | NAMES_STD == "gb"
replace NAMES_STD = "United States" if NAMES_STD == "us"
replace NAMES_STD = "United States Virgin Islands" if NAMES_STD == "vi"
replace NAMES_STD = "Uruguay" if NAMES_STD == "uy"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "uz"
replace NAMES_STD = "Vanuatu" if NAMES_STD == "vu"
replace NAMES_STD = "Vatican" if NAMES_STD == "va"
replace NAMES_STD = "Venezuela" if NAMES_STD == "ve"
replace NAMES_STD = "Vietnam" if NAMES_STD == "vn"
replace NAMES_STD = "Wallis and Futuna" if NAMES_STD == "wf"
replace NAMES_STD = "Western Sahara" if NAMES_STD == "eh"
replace NAMES_STD = "Yemen" if NAMES_STD == "ye"
replace NAMES_STD = "Yugoslavia" if NAMES_STD == "cs" | NAMES_STD == "rs"
replace NAMES_STD = "Zambia" if NAMES_STD == "zm"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "zw"

end
exit
