        capture erase mymodels.sters
        capture erase mymodels.dta
        capture erase example.txt
        capture erase example.html
        capture erase example.csv
        capture erase example.rtf
        capture erase example.tex
        capture erase example.pdf
        capture erase example.aux
        capture erase example.log
        capture erase _example.txt
        capture erase _example1.tex
        capture erase _example2.tex
